// SPDX-License-Identifier: MIT

package crypto

import "fmt"

// GenerateTransferKeyPair advertises transfer-v3 support in the unused high bit
// of the X25519 public-key encoding. RFC 7748 section 5 requires DH decoders to
// mask this bit; canonical public keys generated by older peers leave it clear.
// https://www.rfc-editor.org/rfc/rfc7748#section-5
//
// Crucially, SP2P (including v0.4.0) binds the ORIGINAL public-key bytes into
// HKDF and key confirmation. Do not normalize the advertised bytes there: that
// binding makes stripping/adding the capability fail authentication, including
// when both peers' markers are stripped. The private key and DH are unchanged.
func GenerateTransferKeyPair() (*KeyPair, error) {
	kp, err := GenerateKeyPair()
	if err != nil {
		return nil, err
	}
	kp.Public[KeySize-1] |= 0x80
	return kp, nil
}

// TransferProtocol selects the highest mutually supported transfer version.
// The result is provisional until candidate/key confirmation succeeds. No
// data may be transferred, or negotiated version reported, before that proof.
func TransferProtocol(senderPub, receiverPub []byte) (int, error) {
	if len(senderPub) != KeySize || len(receiverPub) != KeySize {
		return 0, fmt.Errorf("protocol negotiation requires 32-byte public keys")
	}
	if senderPub[KeySize-1]&receiverPub[KeySize-1]&0x80 != 0 {
		return 3, nil
	}
	return 2, nil
}
