version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      npm-packages:
        patterns:
          - "*"
