#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# render.sh — render one package-manager manifest, without publishing it.
#
# Usage: render.sh <channel> <version> <baseURL> <checksums-file> <outdir>
#
#   channel         homebrew | scoop | aur | chocolatey
#                   (winget is rendered by its own GitHub Action, not here.)
#   version         Plain X.Y.Z version, no "v" prefix (e.g. 0.6.3).
#   baseURL         Base URL assets are downloaded from, no trailing slash
#                   (e.g. https://github.com/zyno-io/sp2p/releases/download/v0.6.3,
#                   or a local http.server URL for a goreleaser snapshot).
#   checksums-file  Path to a checksums.txt to resolve sha256 values from.
#                   Accepts both release.yml's "<sha>  ./<file>" form and a
#                   bare goreleaser snapshot's "<sha>  <file>" form (and a
#                   binary-mode "*" prefix), so this script renders identical
#                   bytes whether it's fed a real release's checksums.txt or
#                   a local snapshot's.
#   outdir          Directory to write the rendered manifest file(s) into
#                   (created if missing). Holds only this channel's rendered
#                   files — nothing else is ever written there.
#
# This is the single rendering code path shared by publish-packages.yml (the
# manual, maintainer-dispatched publish workflow) and packaging-validate.yml
# (CI validation, no publishing, no secrets) — so both render byte-identical
# manifests from the same arguments. Never publishes anything itself: it only
# writes files.
#
# Hermetic: no network, git, gh, or makepkg — including for the aur channel's
# .SRCINFO, which is generated by a small, format-pinned function here rather
# than by shelling out to `makepkg --printsrcinfo` (which also refuses to run
# as root, so it isn't available in every context this script runs in). The
# aur validator job(s) still run real `makepkg --printsrcinfo` and diff it
# against this file, so a future libmakepkg format change is caught, not
# silently trusted.

set -euo pipefail

usage() {
  echo "Usage: $0 <homebrew|scoop|aur|chocolatey> <version> <baseURL> <checksums-file> <outdir>" >&2
  exit 2
}
die() { echo "::error::$*" >&2; exit 2; }

[ "$#" -eq 5 ] || usage
CHANNEL="$1" VERSION="$2" BASE_URL="$3" CHECKSUMS="$4" OUTDIR="$5"

case "$CHANNEL" in homebrew | scoop | aur | chocolatey) ;; *) usage ;; esac
# Same rule publish-packages.yml's validate-release job already enforces on
# the tag; render.sh double-checks it since packaging-validate.yml can call
# this directly with a snapshot version.
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "version must be X.Y.Z (got '$VERSION')"
[[ "$BASE_URL" =~ ^https?:// ]] || die "baseURL must be http(s) (got '$BASE_URL')"
[[ "$BASE_URL" != */ ]] || die "baseURL must not end with '/' (got '$BASE_URL')"
case "$BASE_URL" in *[[:space:]\"\'\\]*) die "baseURL must not contain whitespace, quotes, or backslashes" ;; esac
[ -r "$CHECKSUMS" ] || die "checksums file not readable: $CHECKSUMS"

# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

REPO="zyno-io/sp2p"
# publish-packages.yml only ever dispatches from a tag matching
# ^v\d+\.\d+\.\d+$, and VERSION is always that tag with the "v" stripped
# (see validate-release), so this reconstruction is exact, not a guess.
TAG="v${VERSION}"

mkdir -p "$OUTDIR"
OUTPUTS=() # files written, relative to $OUTDIR — logged at the end for comparison

render_homebrew() {
  local SHA_DARWIN_ARM64 SHA_DARWIN_AMD64 SHA_LINUX_ARM64 SHA_LINUX_AMD64
  SHA_DARWIN_ARM64="$(sha sp2p_darwin_arm64.tar.gz)"
  SHA_DARWIN_AMD64="$(sha sp2p_darwin_amd64.tar.gz)"
  SHA_LINUX_ARM64="$(sha sp2p_linux_arm64.tar.gz)"
  SHA_LINUX_AMD64="$(sha sp2p_linux_amd64.tar.gz)"
  cat >"$OUTDIR/sp2p.rb" <<FORMULA
class Sp2p < Formula
  desc "Secure peer-to-peer file transfer"
  homepage "https://sp2p.io"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE_URL}/sp2p_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
    on_intel do
      url "${BASE_URL}/sp2p_darwin_amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/sp2p_linux_arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
    on_intel do
      url "${BASE_URL}/sp2p_linux_amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end
  end

  def install
    bin.install "sp2p"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sp2p version")
  end
end
FORMULA
  OUTPUTS=(sp2p.rb)
}

render_scoop() {
  local SHA_AMD64 SHA_ARM64
  SHA_AMD64="$(sha sp2p_windows_amd64.zip)"
  SHA_ARM64="$(sha sp2p_windows_arm64.zip)"
  cat >"$OUTDIR/sp2p.json" <<MANIFEST
{
  "version": "${VERSION}",
  "architecture": {
    "64bit": {
      "url": "${BASE_URL}/sp2p_windows_amd64.zip",
      "hash": "${SHA_AMD64}"
    },
    "arm64": {
      "url": "${BASE_URL}/sp2p_windows_arm64.zip",
      "hash": "${SHA_ARM64}"
    }
  },
  "bin": "sp2p.exe",
  "homepage": "https://sp2p.io",
  "license": "MIT",
  "description": "Secure peer-to-peer file transfer",
  "checkver": {
    "github": "https://github.com/zyno-io/sp2p"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/zyno-io/sp2p/releases/download/v\$version/sp2p_windows_amd64.zip"
      },
      "arm64": {
        "url": "https://github.com/zyno-io/sp2p/releases/download/v\$version/sp2p_windows_arm64.zip"
      }
    }
  }
}
MANIFEST
  OUTPUTS=(sp2p.json)
}

render_aur() {
  local SHA_AMD64 SHA_ARM64
  SHA_AMD64="$(sha sp2p_linux_amd64.tar.gz)"
  SHA_ARM64="$(sha sp2p_linux_arm64.tar.gz)"
  cat >"$OUTDIR/PKGBUILD" <<EOF
# Maintainer: Zyno Consulting <oss at zyno dot io>
pkgname=sp2p-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc="Secure peer-to-peer file transfer"
arch=('x86_64' 'aarch64')
url="https://sp2p.io"
license=('MIT')
provides=('sp2p')
conflicts=('sp2p')
source_x86_64=("${BASE_URL}/sp2p_linux_amd64.tar.gz")
source_aarch64=("${BASE_URL}/sp2p_linux_arm64.tar.gz")
sha256sums_x86_64=('${SHA_AMD64}')
sha256sums_aarch64=('${SHA_ARM64}')

package() {
  install -Dm755 sp2p "\${pkgdir}/usr/bin/sp2p"
  install -Dm644 LICENSE "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
EOF
  # Exactly what `makepkg --printsrcinfo` emits for the PKGBUILD above
  # (libmakepkg/srcinfo.sh: tab-indented attributes, per-arch attributes
  # after the shared ones, a blank line, then the pkgname section) —
  # confirmed byte-for-byte against the published sp2p-bin AUR package's
  # real .SRCINFO. The aur validator job(s) re-derive this with a real
  # `makepkg --printsrcinfo` and diff it against this file, so a future
  # libmakepkg format change would be caught there, not silently trusted.
  {
    printf 'pkgbase = %s\n' sp2p-bin
    printf '\t%s = %s\n' \
      pkgdesc "Secure peer-to-peer file transfer" \
      pkgver "$VERSION" \
      pkgrel 1 \
      url "https://sp2p.io" \
      arch x86_64 \
      arch aarch64 \
      license MIT \
      provides sp2p \
      conflicts sp2p \
      source_x86_64 "${BASE_URL}/sp2p_linux_amd64.tar.gz" \
      sha256sums_x86_64 "$SHA_AMD64" \
      source_aarch64 "${BASE_URL}/sp2p_linux_arm64.tar.gz" \
      sha256sums_aarch64 "$SHA_ARM64"
    printf '\npkgname = %s\n' sp2p-bin
  } >"$OUTDIR/.SRCINFO"
  OUTPUTS=(PKGBUILD .SRCINFO)
}

render_chocolatey() {
  local SHA_AMD64
  SHA_AMD64="$(sha sp2p_windows_amd64.zip)"
  mkdir -p "$OUTDIR/tools"
  cat >"$OUTDIR/sp2p.nuspec" <<NUSPEC
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>sp2p</id>
    <version>${VERSION}</version>
    <title>SP2P - Secure P2P File Transfer</title>
    <authors>Zyno Consulting</authors>
    <owners>zyno-io</owners>
    <iconUrl>https://raw.githubusercontent.com/zyno-io/sp2p/main/web/icon.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <licenseUrl>https://github.com/zyno-io/sp2p/blob/main/LICENSE</licenseUrl>
    <projectUrl>https://sp2p.io</projectUrl>
    <projectSourceUrl>https://github.com/zyno-io/sp2p</projectSourceUrl>
    <packageSourceUrl>https://github.com/zyno-io/sp2p/tree/main/.github/workflows</packageSourceUrl>
    <bugTrackerUrl>https://github.com/zyno-io/sp2p/issues</bugTrackerUrl>
    <description>Secure peer-to-peer file transfer. End-to-end encrypted, file data flows directly between peers via WebRTC.</description>
    <summary>Secure peer-to-peer file transfer</summary>
    <releaseNotes>https://github.com/${REPO}/releases/tag/${TAG}</releaseNotes>
    <tags>file-transfer p2p webrtc cli security encryption</tags>
  </metadata>
</package>
NUSPEC
  # LF line endings (the pre-render.sh pwsh Set-Content wrote CRLF);
  # PowerShell treats both the same.
  cat >"$OUTDIR/tools/chocolateyInstall.ps1" <<INSTALL
\$ErrorActionPreference = 'Stop'
\$toolsDir = Split-Path -Parent \$MyInvocation.MyCommand.Definition
\$packageArgs = @{
  packageName    = 'sp2p'
  url64bit       = '${BASE_URL}/sp2p_windows_amd64.zip'
  unzipLocation  = \$toolsDir
  checksum64     = '${SHA_AMD64}'
  checksumType64 = 'sha256'
}
Install-ChocolateyZipPackage @packageArgs
INSTALL
  OUTPUTS=(sp2p.nuspec tools/chocolateyInstall.ps1)
}

"render_$CHANNEL"

# Log hashes (stderr, never files — $OUTDIR must hold only this channel's
# manifest files) so a publish run and a validation run can be compared.
for f in "${OUTPUTS[@]}"; do
  printf 'rendered %s  %s/%s\n' "$(sha256_file "$OUTDIR/$f")" "$CHANNEL" "$f" >&2
done
